import { Josefin_Sans, Cormorant_Garamond } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.scss';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';
import Banner from '@/components/header/Banner';
import Lenis from '@/components/Lenis';
import { ContactDialogProvider } from '@/components/context/ContactDialogProvider';
import Contact from '@/components/contact/Contact';

const josefin = Josefin_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-josefin',
  weight: ['300', '400'],
});

const cormorant = Cormorant_Garamond({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-cormorant',
  weight: ['400', '500'],
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${josefin.variable} ${cormorant.variable}`}>
        <Lenis>
          <ContactDialogProvider>
            <Banner />
            <Header />
            {children}
            <Footer />
            <Contact />
          </ContactDialogProvider>
        </Lenis>
      </body>
    </html>
  );
}
